deploy:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - whoami
  script:
    - cd /app/www/html/admin_html
    - pwd
    - git status
    - git fetch
    - git checkout master
  only:
    - master
